version: '3'
services:
  app-sqlalchemy:
    container_name: stac-portal-backend
    image: oseoinfraacrstaging.azurecr.io/stac-portal-backend:6363dd7
    platform: linux/amd64
    network_mode: host
    env_file:
      - .env
