version: '3'
services:
  stac-portal-backend:
    container_name: stac-portal-backend
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file:
      - .env
    network_mode: host